variables:
  CONTAINER_NAME: $CI_REGISTRY_IMAGE
  SERVER_HOST: !REPLACE_IT!

stages:
  - build
  - deploy

build-docker:
  image: docker:stable
  services:
    - docker:dind
  stage: build
  when: manual
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CONTAINER_NAME:latest || true
    - docker build --cache-from $CONTAINER_NAME:latest -t $CONTAINER_NAME:latest .
    - docker push $CONTAINER_NAME:latest

deploy:
  image: alpine
  stage: deploy
  script:
    - wget -qO- $SERVER_HOST/$CI_PROJECT_NAME/update
  when: manual
  only:
    - master
